#pragma once
#include <te.hpp>

#define TE_COLORDEPTH 4

#define TE_RENDERER_NO_RENDERER 0
#define TE_RENDERER_SOFTWARE_RASTERIZER 1
#define TE_RENDERER_SOFTWARE_RASTERIZER_SINGLE_THREAD 2

//fonts
#define TE_FONT_MIN_SIZE 6
#define TE_FONT_MAX_SIZE 108